version: 2

build:
   os: ubuntu-24.04
   tools:
      python: "3.13"
   jobs:
      create_environment:
         - asdf plugin add pixi
         - asdf install pixi latest
         - asdf global pixi latest
      install:
         # assuming you have an environment called "docs"
         - pixi install -e docs
      build:
         html:
            - NO_COLOR=1 pixi run -e docs mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
